# Generated by Django 3.2.20 on 2023-08-19 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_course_session_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='course_name',
        ),
    ]
