# Generated by Django 3.2.20 on 2023-08-20 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_student_add'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student_Add',
            new_name='Student',
        ),
    ]
