# Generated by Django 3.2.20 on 2023-08-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20230822_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='session_year',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
